num_players = input('How many players?')

A = int(input("How many A's: "))
B = int(input("How many B's: "))
C = int(input("How many C's: "))
D = int(input("How many D's: "))
E = int(input("How many E's: "))
F = int(input("How many F's: "))
G = int(input("How many G's: "))
H = int(input("How many H's: "))
I = int(input("How many I's: "))
J = int(input("How many J's: "))
K = int(input("How many K's: "))
L = int(input("How many L's: "))
M = int(input("How many M's: "))
N = int(input("How many N's: "))
O = int(input("How many O's: "))
P = int(input("How many P's: "))
Q = int(input("How many Q's: "))
R = int(input("How many R's: "))
S = int(input("How many S's: "))
T = int(input("How many T's: "))
U = int(input("How many U's: "))
V = int(input("How many V's: "))
W = int(input("How many W's: "))
X = int(input("How many X's: "))
Y = int(input("How many Y's: "))
Z = int(input("How many Z's: "))

total = (A * 13) + (B * 3) + (C * 3) + (D * 6) + (E * 18) + (F * 3) + (G * 4) + (H * 3) + (I * 12) + (J * 2) + (K * 2) + (L * 5) + (M * 3) + (N * 8) + (O * 11) + (P * 3) + (Q * 2) + (R * 9) + (S * 6) + (T * 9) + (U * 6) + (V * 3) + (W * 3) + (X * 2) + (Y * 3) + (Z * 2)
print('Your total score is:', total)
